### ISSUE TITLE
Unclear debug instructions in Cloning Medium article

### ISSUE THREAD

**Issue by philraj** [quilljs/quilljs.github.io#22]
Hi, the _Clone Medium with Parchment_ article has some unclear instructions about playing with the CodePen examples in the browser console. For example, in the _Basic Formatting_ section it says:

> Open your developer console and try out Quill’s APIs on your new bold and italic formats! Make sure to set the context to the correct CodePen iframe to be able to access the quill variable in the demo.

But the `quill` variable isn't on the window object, so how would the dev console have access to it even if the correct iframe is set as the execution context?

**Comment by jhchen** [comment]
The code example is `var quill = new Quill('#editor');` which does get stored globally as that is a characteristic of `var` in an unscoped context. The particular Codepen uses `let` which is not supposed to but does anyways possibly because the way Babel is converting this to `var` but regardless the demo does work as documented. I'll change the `let` to `var` ensure this for future Babel/Codepen versions.

**Comment by philraj** [comment]
Ah I see the problem now. When the Codepen project is open on their website, the code is inserted in a normal script tag. When embedding in your docs page, they put it in a `<script type="module">`, which prevents top-level variables from mixing into the global scope.

When using module type script tags, you have to explicitly attach variables to the window object when you want them to be global. (I just tried it with the change from `let` to `var` and it still doesn't work, so it needs to also have a `window.quill = quill` for the instructions in the tutorial to work).
